### ISSUE TITLE
ModuleNotFoundError: No module named 'nornir_csv.plugins'

### ISSUE THREAD

**Issue by jnyany** [matman26/nornir_csv#1]
Hi, thanks for such plugin, I was looking for something like this for sometime. It is really simple, but when I try I get this error

ModuleNotFoundError: No module named 'nornir_csv.plugins'

I have the package installed though

Package            Version
------------------ --------
importlib-metadata 4.10.1
mypy-extensions    0.4.3
nornir             3.2.0
nornir-csv         0.1.3

repo for reference https://github.com/jbl241987/Nornir_Project.git

**Comment by matman26** [comment]
Hello @jbl241987, something went wrong with the packaging  for the current release on PyPI. I'll try to prepare a new release for later today and incorporate some of improvements from latest commits. In the meantime, you can get the latest version as-is by cloning this repo inside your current project and adjusting the import to be `from nornir_csv.nornir_csv.plugins.inventory import CsvInventory`:

```bash
git clone https://github.com/matman26/nornir_csv.git
```

**Comment by jnyany** [comment]
Thank you @matman26 it is working that way. Once fixed, I will try again with plugin installed.

**Comment by jnyany** [comment]
One request, if this plugin can work for excel, then it will more useful. Many of my end users prefer excel and I guess not much different from CSV class.

**Comment by matman26** [comment]
Fixed. From your terminal please upgrade the package to v0.2:
```bash
pip install --upgrade nornir_csv
```
Currently it's still possible to use Excel spreadsheets by exporting into CSV, so I don't see a compelling reason to implement it right now. Might take a look into it at a later date if more people are interested.

**Comment by jnyany** [comment]
Perfect, this worked for me now.
