### ISSUE TITLE
[Bug] Default value handling for Hosts

### ISSUE THREAD

**Issue by matman26** [matman26/nornir_csv#3]
thanks @matman26 , I will definitely try this option also.

One more query, I have used hosts.csv as exactly shown in Readme. But i want to remove username and password from hosts.csv and keep only in defaults.csv or groups.csv

I tried that but that doesn't work. Seems it is mandatory in hosts.csv. 

How can I make it work?

_Originally posted by @jbl241987 in https://github.com/matman26/nornir_csv/issues/2#issuecomment-1019105423_

**Comment by matman26** [comment]
Fixed by release 0.2.2.
Please update the PyPI package:
```
pip install --upgrade nornir-csv
```

**Comment by jnyany** [comment]
Perfect..! I tested this on both Groups and Defaults, worked perfectly.
